kind: PersistentVolume
apiVersion: v1
metadata:
   name: pv0001
   labels:
      type: local

spec:
   capacity:
      storage: 100Gi
   accessModes:
   - ReadWriteOnce
   storageClassName: elasticsearch-gp2
   hostPath:
       path: "/tmp/elastic01"

---
kind: PersistentVolume
apiVersion: v1
metadata:
   name: pv0002
   labels:
      type: local

spec:
   capacity:
      storage: 100Gi
   accessModes:
   - ReadWriteOnce
   storageClassName: elasticsearch-gp2
   hostPath:
       path: "/tmp/elastic02"

---
kind: PersistentVolume
apiVersion: v1
metadata:
   name: pv0003
   labels:
      type: local

spec:
   capacity:
      storage: 100Gi
   accessModes:
   - ReadWriteOnce
   storageClassName: elasticsearch-gp2
   hostPath:
       path: "/tmp/elastic03"

